# Generated by Django 5.1.4 on 2025-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
